"""empty message

Revision ID: 78deb6036eed
Revises: 
Create Date: 2024-11-16 13:32:30.010997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78deb6036eed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=30), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
